# Header
menu:
  Home: /
  Archives: /archives
  About: "#"
  #Tags: /tags
  #Categories: /categories
  My books: "#"
  #Github:
  #  url: https://github.com/oddscript
  #  icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: Odd Script

# URL of the Home page image
index_cover: /img/cover.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-108382845-1

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url: https://twitter.com/oddscript
twitter_handle: oddscript
facebook_url:
github_url: https://github.com/oddscript
gitlab_url:
linkedin_url:
mailto: